import type { Metadata } from "next";

import "./globals.css";
import ComponentsPage from "@/components/page/Page";


export const metadata: Metadata = {
  title: "First-work",
  description: "Generated by create next app",
};

export default function RootLayout(){
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
            <ComponentsPage />
        </div>
      </body>
    </html>
  );
}
